# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each 6 hours)
  # schedule: [{cron: "0 4,10,16,22 * * *"}]
  # Schedule updates (each 24 hours)
  schedule: [{cron: "0 16 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Panxuc
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_octicon: yes
          config_timezone: Etc/GMT-8
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: vhdl, jupyter notebook
          plugin_languages_skipped: open531/XPrism
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_details: lines, bytes-size
          plugin_languages_indepth: no
          plugin_languages_limit: 8
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          # plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          # plugin_steam: yes
          # plugin_steam_achievements_limit: 2
          # plugin_steam_games_limit: 2
          # plugin_steam_playtime_threshold: 2
          # plugin_steam_recent_games_limit: 2
          # plugin_steam_sections: player, most-played, recently-played
          # plugin_steam_user: "76561198931295053"
          repositories_forks: yes
